import { propertyTypeEnum } from "ym-web-view"
import React from "react";
import { searchOptionWidth } from "@/utils/constant";

export enum ETaskStatus {
    'nomal' = 'nomal',
    'discard' = 'discard', // 后者替换成后端字符串
}


export const searchOptions = [
    {
        type: propertyTypeEnum.search,
        name: 'id',
        placeholder: '请输入用户名',
        width: searchOptionWidth,
        aliasText: 'text',
    },
]

// 表头
export const columns = [
    {
        title: '角色名',
        dataIndex: 'name',
        key: 'name',
        width: 80,
        ellipsis: true,
    },
    {
        title: '角色标识',
        dataIndex: 'label',
        key: 'label',
        width: 80,
        ellipsis: true,
    },
    {
        title: '描述',
        dataIndex: 'description',
        key: 'description',
        width: 300,
        ellipsis: true,
    },
]
export const tableTestData = [
    {
        key: '1',
        id: 1,
        a: '1',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        h: 'nomal',
    },
    {
        key: '2',
        a: '2',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '已完成',
        id: 2,
        h: 'nomal',
    },
    {
        key: '3',
        a: '3',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '待执行',
        id: 3,
        h: 'discard',
    },
    {
        key: '4',
        a: '4',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '异常',
        id: 4,
        h: 'nomal',
    },
    {
        key: '5',
        a: '5',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '强制结束',
        id: 5,
        h: 'nomal',
    },
    {
        key: '6',
        a: '6',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        id: 6,
        h: 'nomal',
    },
    {
        key: '7',
        a: '7',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        id: 7,
        h: 'nomal',
    },
    {
        key: '8',
        a: '8',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        id: 8,
        h: 'nomal',
    },
    {
        key: '9',
        a: '9',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        id: 9,
        h: 'nomal',
    },
    {
        key: '10',
        a: '10',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        id: 10,
        h: 'nomal',
    },
    {
        key: '11',
        id: 11,
        a: '11',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '执行中',
        h: 'nomal',
    },
    {
        key: '12',
        a: '12',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '已完成',
        id: 12,
        h: 'nomal',
    },
    {
        key: '13',
        a: '13',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '待执行',
        id: 13,
        h: 'nomal',
    },
    {
        key: '14',
        a: '4',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '异常',
        id: 14,
        h: 'nomal',
    },
    {
        key: '15',
        a: '5',
        b: '2023-09-19',
        c: '10kv设备室日常巡检1042',
        d: '日常巡检',
        e: '10kv设备室',
        f: '16:00',
        g: '强制结束',
        id: 15,
        h: 'nomal',
    },
]